# debian/rules would use this Makefile if named so over the default debuild
# make targets, thus we should avoid naming this file Makefile

build_init: # rerun to copy the files into the builder
	docker build -t debian-package-builder .

build_run: # builds in a docker container and output to the ./out/ dir
	mkdir -p $$(pwd)/out
	docker run --rm -v $$(pwd)/out:/pkg debian-package-builder

build_debug: # run a bash into the container for debugging
	mkdir -p $$(pwd)/out
	docker run -it --rm -v $$(pwd)/out:/pkg debian-package-builder /bin/bash

build_clean:
	docker rmi debian-package-builder
